# Streamlit secrets configuration for Miva Dashboard
# For Streamlit Cloud deployment, add these secrets in your app settings
# For local development, create this file in .streamlit/secrets.toml

[database]
host = "16.170.143.253"
port = 5432
user = "admin"
password = "password123"
database = "miva_ai_db"

[auth]
admin_username = "miva_admin"
admin_password = "password123"

# Optional: Add additional configuration
[app]
environment = "production"
debug_mode = false
